# Generated by Django 5.2 on 2025-08-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_for', models.CharField(max_length=40)),
                ('identifier', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=100)),
                ('otp_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('INITIALIZE ', 'Initialize'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired')], default='INITIALIZE ', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verfied_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'Otps',
                'db_table': 'otp_db',
            },
        ),
    ]
