# Generated by Django 5.2 on 2025-08-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyX_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_model',
            name='otp_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
